version: '3'

services:
  nginx:
    image: nginx
    expose:
     - 80
    volumes:
      - ./sites:/etc/nginx/conf.d
    links:
      - nodejs:nodejs
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=braintree.broccody.com
      - LETSENCRYPT_HOST=braintree.broccody.com
      - LETSENCRYPT_EMAIL=yim.boonyarit@gmail.com
    container_name: braintree-server-nginx

  nodejs:
    build: ./app
    tty: true
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    network_mode: bridge
    container_name: braintree-server-nodejs