version: '3'

services:
  braintree-server-nginx:
    image: nginx
    expose:
     - 80
    volumes:
      - ./sites:/etc/nginx/conf.d
    links:
      - braintree-server-nodejs:nodejs
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=braintree.broccody.com
      - LETSENCRYPT_HOST=braintree.broccody.com
      - LETSENCRYPT_EMAIL=yim.boonyarit@gmail.com
    container_name: braintree-server-nginx

  braintree-server-nodejs:
    build: ./app
    tty: true
    expose:
      - 3000
    ports: 
      - 3000:3000
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    network_mode: bridge
    container_name: braintree-server-nodejs